### ISSUE TITLE
 help visualizing data in mongoDB using Docker [PT-BR]

### ISSUE THREAD

**Issue by andrefelipebarros** [Math-Z/elementary_school_project#1]
1. **Verificar os containers em execução**:
   ```bash
   docker ps
   ```
   Isso lista todos os containers ativos, mostrando o ID, nome, status e porta mapeada.

2. **Verificar todos os containers (ativos e inativos)**:
   ```bash
   docker ps -a
   ```
   Esse comando vai listar tanto os containers em execução quanto os que já foram parados.

3. **Verificar os logs de um container específico**:
   Se você quiser ver os logs de um container (por exemplo, do seu front-end, back-end ou MongoDB):
   ```bash
   docker logs <nome_do_container>
   ```
   Substitua `<nome_do_container>` pelo nome ou ID do container.

   Para seguir os logs em tempo real (como um `tail -f`):
   ```bash
   docker logs -f <nome_do_container>
   ```

4. **Verificar o status dos volumes**:
   Caso você queira ver volumes (como o MongoDB), pode listar todos os volumes criados:
   ```bash
   docker volume ls
   ```

5. **Acessar o terminal de um container em execução**:
   Se quiser acessar o terminal de um container em execução (útil para verificar logs ou configurações diretamente):
   ```bash
   docker exec -it <nome_do_container> bash
   ```
   Isso abre um terminal `bash` dentro do container. Para MongoDB, o comando pode ser `mongo` em vez de `bash` para entrar no shell do MongoDB.

Esses comandos vão te ajudar a monitorar e gerenciar seus containers e serviços no Docker.

**Comment by Math-Z** [comment]
VALEU

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive
